name: CI/CD Pipeline

# 1. Define when this pipeline should run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      spec_path:
        description: 'Cypress spec file to run'
        required: true
        default: 'staging'
        type: choice     # This forces GitHub to display a dropdown select menu
        options:
          - development
          - staging
          - production

# 2. Define the automation tasks
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SPEC_PATH: ${{ github.event.inputs.spec_path || inputs.spec_path || 'cypress/e2e/authentication/login.cy.js' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx cypress run --browser electron --spec "$SPEC_PATH"

      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying application..."
